import type {
  CandidateDocumentItem,
  CandidateTaskItem,
  CompletedCandidateRow,
} from "../types/preEnrollment.types";

export const completedCandidates: CompletedCandidateRow[] = [
  {
    id: 1,
    name: "Anusha Mavellapalli",
    email: "anurauiuxdesigner@gmail.com",
    mobile: "8522918639",
    joiningDate: "13/Mar/2026",
    designation: "Software Engineer",
    employeeId: "294640",
    reportingTo: "RAJESH UBBAPALLY",
    address: "12-4-5, Hill View Apartments",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    zipCode: "500081",
    profilePhotoUrl: "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=240&q=80",
    dob: "20/10/1993",
    gender: "Male",
    maritalStatus: "Married",
    qualification: "B.Tech Computer Science",
    status: "1/5",
    progress: 20,
  },
  {
    id: 2,
    name: "Prathyusha Reddy",
    email: "iamprathyushareddy@gmail.com",
    mobile: "7671020464",
    joiningDate: "25/Mar/2026",
    designation: "UI/UX Designer",
    employeeId: "294641",
    reportingTo: "RAJESH UBBAPALLY",
    address: "Plot 45, Green Valley",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    zipCode: "500045",
    profilePhotoUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=240&q=80",
    dob: "15/08/1996",
    gender: "Female",
    maritalStatus: "Single",
    qualification: "B.Des Visual Communication",
    status: "2/5",
    progress: 40,
  },
  {
    id: 3,
    name: "Chithanuri Sowmya",
    email: "sowmyagupta2000@gmail.com",
    mobile: "8096474350",
    joiningDate: "25/Mar/2026",
    designation: "HR Coordinator",
    employeeId: "294642",
    reportingTo: "RAJESH UBBAPALLY",
    address: "Block C, Silver Oak Apartments",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    zipCode: "500076",
    profilePhotoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=240&q=80",
    dob: "07/11/1994",
    gender: "Female",
    maritalStatus: "Single",
    qualification: "MBA Human Resources",
    status: "2/5",
    progress: 40,
  },
  {
    id: 4,
    name: "Rakshitha Golagani",
    email: "rakshithagolagani2004@gmail.com",
    mobile: "7702070627",
    joiningDate: "06/Apr/2026",
    designation: "Backend Engineer",
    employeeId: "294643",
    reportingTo: "RAJESH UBBAPALLY",
    address: "H.No. 9-12-34, Sunrise Colony",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    zipCode: "500072",
    profilePhotoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80",
    dob: "03/04/1995",
    gender: "Female",
    maritalStatus: "Single",
    qualification: "MCA",
    status: "3/5",
    progress: 60,
  },
  {
    id: 5,
    name: "Karicheti Babu",
    email: "venkata.suresh25k@gmail.com",
    mobile: "8074069190",
    joiningDate: "08/Apr/2026",
    designation: "Technical Lead",
    employeeId: "294644",
    reportingTo: "RAJESH UBBAPALLY",
    address: "8-2-352, Street No. 7",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    zipCode: "500049",
    profilePhotoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&q=80",
    dob: "12/09/1989",
    gender: "Male",
    maritalStatus: "Married",
    qualification: "B.Tech Electrical Engineering",
    status: "1/5",
    progress: 20,
  },
  {
    id: 6,
    name: "Naveen Penaganti",
    email: "naveenpenaganti123@gmail.com",
    mobile: "9951018954",
    joiningDate: "06/Apr/2026",
    designation: "Quality Analyst",
    employeeId: "294645",
    reportingTo: "RAJESH UBBAPALLY",
    address: "20-3-55, Lakeview Residency",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    zipCode: "500067",
    profilePhotoUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=240&q=80",
    dob: "01/01/1993",
    gender: "Male",
    maritalStatus: "Single",
    qualification: "B.Sc Computer Science",
    status: "1/5",
    progress: 20,
  },
  {
    id: 7,
    name: "Hindusena Varadarajula",
    email: "hindunaidu497@gmail.com",
    mobile: "8008906785",
    joiningDate: "06/Apr/2024",
    designation: "Operations Specialist",
    employeeId: "294646",
    reportingTo: "RAJESH UBBAPALLY",
    address: "5-10-20, Corporate Heights",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    zipCode: "500084",
    profilePhotoUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=240&q=80",
    dob: "28/02/1990",
    gender: "Male",
    maritalStatus: "Married",
    qualification: "MBA Operations",
    status: "3/5",
    progress: 60,
  },
];

export const teamTasks: CandidateTaskItem[] = [
  { id: "team-1", activity: "Welcome Mail", status: "Completed" },
  { id: "team-2", activity: "Candidate Portal", status: "Completed" },
  { id: "team-3", activity: "Asset Issue", status: "Completed" },
  { id: "team-4", activity: "Training Request", status: "Completed" },
  { id: "team-5", activity: "Intimation Mail", status: "Completed" },
];

export const candidateTasks: CandidateTaskItem[] = [
  { id: "candidate-1", activity: "Welcome Mail", status: "Completed" },
  { id: "candidate-2", activity: "Candidate Portal", status: "Completed" },
];

export const candidateDocuments: CandidateDocumentItem[] = [
  { id: "doc-1", label: "Confirmation Letter", fileName: "confirmation-letter.pdf" },
  { id: "doc-2", label: "PF Declaration", fileName: "pf-declaration.pdf" },
  { id: "doc-3", label: "Payment of Gratuity Form", fileName: "gratitude-form.pdf" },
  { id: "doc-4", label: "Form-11", fileName: "form-11.pdf" },
];

export function getCandidateById(id: number) {
  return completedCandidates.find((candidate) => candidate.id === id);
}

