export const DASHBOARD_STATS = [
  {
    id: 1,
    title: "Total Candidates",
    value: 120,
    icon: "Users",
    iconBg: "#DBEAFE",
    iconColor: "#2563EB",
  },
  {
    id: 2,
    title: "In Progress",
    value: 42,
    icon: "Clock3",
    iconBg: "#FEF3C7",
    iconColor: "#D97706",
  },
  {
    id: 3,
    title: "Completed",
    value: 78,
    icon: "CircleCheckBig",
    iconBg: "#DCFCE7",
    iconColor: "#16A34A",
  },
  {
    id: 4,
    title: "Pending Approval",
    value: 18,
    icon: "ClipboardCheck",
    iconBg: "#FCE7F3",
    iconColor: "#DB2777",
  },
  {
    id: 5,
    title: "Rejected",
    value: 9,
    icon: "UserX",
    iconBg: "#FEE2E2",
    iconColor: "#DC2626",
  },
  {
    id: 6,
    title: "Documents Uploaded",
    value: 95,
    icon: "FileText",
    iconBg: "#E0F2FE",
    iconColor: "#0284C7",
  },
];
